providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.7"
BE_ENV = 'prod'

[phases.custom_install]
cmds = ["pip3 install gunicorn"]
dependsOn = ['install']

[phases.test]
cmds = ["export BE_ENV=test", "coverage run -m pytest || exit -1", "coverage report", "export BE_ENV=prod"]
dependsOn = ['custom_install']

[start]
cmd = "gunicorn -b 0.0.0.0:8000 'main_run:main_loop()'"
