"""Remove procedure from recipes

Revision ID: d28ef9ede085
Revises: 
Create Date: 2022-10-20 19:03:40.591939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28ef9ede085'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutri_recipes', schema=None) as batch_op:
        batch_op.drop_column('procedure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutri_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
