"""tags

Revision ID: 23e5da469fa7
Revises: 
Create Date: 2023-01-29 19:28:44.238206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e5da469fa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cs_nutri_recipes', 'tags',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('de_nutri_recipes', 'tags',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('en_nutri_recipes', 'tags',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('en_nutri_recipes', 'tags',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('de_nutri_recipes', 'tags',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('cs_nutri_recipes', 'tags',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
